package cz.ondrejvane.griphub.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BoulderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoulderAllPropertiesEquals(Boulder expected, Boulder actual) {
        assertBoulderAutoGeneratedPropertiesEquals(expected, actual);
        assertBoulderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoulderAllUpdatablePropertiesEquals(Boulder expected, Boulder actual) {
        assertBoulderUpdatableFieldsEquals(expected, actual);
        assertBoulderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoulderAutoGeneratedPropertiesEquals(Boulder expected, Boulder actual) {
        assertThat(actual)
            .as("Verify Boulder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoulderUpdatableFieldsEquals(Boulder expected, Boulder actual) {
        assertThat(actual)
            .as("Verify Boulder relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getGrade()).as("check grade").isEqualTo(expected.getGrade()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getSlope()).as("check slope").isEqualTo(expected.getSlope()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoulderUpdatableRelationshipsEquals(Boulder expected, Boulder actual) {
        assertThat(actual)
            .as("Verify Boulder relationships")
            .satisfies(a -> assertThat(a.getWalls()).as("check walls").isEqualTo(expected.getWalls()));
    }
}
