package cz.ondrejvane.griphub.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClimbAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClimbAllPropertiesEquals(Climb expected, Climb actual) {
        assertClimbAutoGeneratedPropertiesEquals(expected, actual);
        assertClimbAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClimbAllUpdatablePropertiesEquals(Climb expected, Climb actual) {
        assertClimbUpdatableFieldsEquals(expected, actual);
        assertClimbUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClimbAutoGeneratedPropertiesEquals(Climb expected, Climb actual) {
        assertThat(actual)
            .as("Verify Climb auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClimbUpdatableFieldsEquals(Climb expected, Climb actual) {
        assertThat(actual)
            .as("Verify Climb relevant properties")
            .satisfies(a -> assertThat(a.getAttempts()).as("check attempts").isEqualTo(expected.getAttempts()))
            .satisfies(a -> assertThat(a.getTopDate()).as("check topDate").isEqualTo(expected.getTopDate()))
            .satisfies(a -> assertThat(a.getRate()).as("check rate").isEqualTo(expected.getRate()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getIsTop()).as("check isTop").isEqualTo(expected.getIsTop()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClimbUpdatableRelationshipsEquals(Climb expected, Climb actual) {
        assertThat(actual)
            .as("Verify Climb relationships")
            .satisfies(a -> assertThat(a.getBoulder()).as("check boulder").isEqualTo(expected.getBoulder()));
    }
}
