package cz.ondrejvane.griphub.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HoldAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoldAllPropertiesEquals(Hold expected, Hold actual) {
        assertHoldAutoGeneratedPropertiesEquals(expected, actual);
        assertHoldAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoldAllUpdatablePropertiesEquals(Hold expected, Hold actual) {
        assertHoldUpdatableFieldsEquals(expected, actual);
        assertHoldUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoldAutoGeneratedPropertiesEquals(Hold expected, Hold actual) {
        assertThat(actual)
            .as("Verify Hold auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoldUpdatableFieldsEquals(Hold expected, Hold actual) {
        assertThat(actual)
            .as("Verify Hold relevant properties")
            .satisfies(a -> assertThat(a.getPhotoCoordinatesX()).as("check photoCoordinatesX").isEqualTo(expected.getPhotoCoordinatesX()))
            .satisfies(a -> assertThat(a.getPhotoCoordinatesY()).as("check photoCoordinatesY").isEqualTo(expected.getPhotoCoordinatesY()))
            .satisfies(a -> assertThat(a.getColumn()).as("check column").isEqualTo(expected.getColumn()))
            .satisfies(a -> assertThat(a.getRow()).as("check row").isEqualTo(expected.getRow()))
            .satisfies(a -> assertThat(a.getHoldType()).as("check holdType").isEqualTo(expected.getHoldType()))
            .satisfies(a -> assertThat(a.getHoldDifficulty()).as("check holdDifficulty").isEqualTo(expected.getHoldDifficulty()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoldUpdatableRelationshipsEquals(Hold expected, Hold actual) {
        assertThat(actual)
            .as("Verify Hold relationships")
            .satisfies(a -> assertThat(a.getWall()).as("check wall").isEqualTo(expected.getWall()));
    }
}
