package cz.ondrejvane.griphub.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WallAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWallAllPropertiesEquals(Wall expected, Wall actual) {
        assertWallAutoGeneratedPropertiesEquals(expected, actual);
        assertWallAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWallAllUpdatablePropertiesEquals(Wall expected, Wall actual) {
        assertWallUpdatableFieldsEquals(expected, actual);
        assertWallUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWallAutoGeneratedPropertiesEquals(Wall expected, Wall actual) {
        assertThat(actual)
            .as("Verify Wall auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWallUpdatableFieldsEquals(Wall expected, Wall actual) {
        assertThat(actual)
            .as("Verify Wall relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getHeight()).as("check height").isEqualTo(expected.getHeight()))
            .satisfies(a -> assertThat(a.getWidth()).as("check width").isEqualTo(expected.getWidth()))
            .satisfies(a -> assertThat(a.getMinSlope()).as("check minSlope").isEqualTo(expected.getMinSlope()))
            .satisfies(a -> assertThat(a.getMaxSlope()).as("check maxSlope").isEqualTo(expected.getMaxSlope()))
            .satisfies(a -> assertThat(a.getRows()).as("check rows").isEqualTo(expected.getRows()))
            .satisfies(a -> assertThat(a.getColumns()).as("check columns").isEqualTo(expected.getColumns()))
            .satisfies(a -> assertThat(a.getPhoto()).as("check photo").isEqualTo(expected.getPhoto()))
            .satisfies(a -> assertThat(a.getPhotoContentType()).as("check photo contenty type").isEqualTo(expected.getPhotoContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWallUpdatableRelationshipsEquals(Wall expected, Wall actual) {
        // empty method
    }
}
